### ISSUE TITLE
Can't get fluidsynth to work

### ISSUE THREAD

**Issue by JakobFelixJulius** [bzamecnik/midi2audio#2]
Hello,
I installed everything according to the instructions (installed fluidsynth via homebrew) and added a custom sound font. Playback via terminal/console is working. But when I am trying to use the midi2audio module in python I always get the following error (using python 3.5 on macOS 10.13) :

```
from midi2audio import FluidSynth
fs = FluidSynth()
fs.play_midi('ahead_on_our_way_piano.mid')
Traceback (most recent call last):

  File "<ipython-input-3-6ff900f0d0db>", line 4, in <module>
    fs.play_midi('ahead_on_our_way_piano.mid')

  File "/Users/user/anaconda3/envs/deeplearning/lib/python3.5/site-packages/midi2audio.py", line 49, in play_midi
    subprocess.call(['fluidsynth', '-i', self.sound_font, midi_file, '-r', str(self.sample_rate)])

  File "/Users/user/anaconda3/envs/deeplearning/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:

  File "/Users/user/anaconda3/envs/deeplearning/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)

  File "/Users/user/anaconda3/envs/deeplearning/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)

FileNotFoundError: [Errno 2] No such file or directory: 'fluidsynth'
```
any help would be appreciated!

**Comment by bzamecnik** [comment]
Hi Jakob, briefly looking at the message, fluidsynth might not be visible
in $PATH to Python. Check that please.

Dne 24. 1. 2018 17:45 napsal uživatel "jakob.sudau" <
notifications@github.com>:

Hello,
I installed everything according to the instructions (installed fluidsynth
via homebrew) and added a custom sound font. Playback via terminal/console
is working. But when I am trying to use the midi2audio module in python I
always get the following error (using python 3.5 on macOS 10.13) :

`from midi2audio import FluidSynth

fs = FluidSynth()
fs.play_midi('ahead_on_our_way_piano.mid')
Traceback (most recent call last):

File "", line 4, in
fs.play_midi('ahead_on_our_way_piano.mid')

File "/Users/user/anaconda3/envs/deeplearning/lib/python3.5/site-packages/midi2audio.py",
line 49, in play_midi
subprocess.call(['fluidsynth', '-i', self.sound_font, midi_file, '-r',
str(self.sample_rate)])

File "/Users/user/anaconda3/envs/deeplearning/lib/python3.5/subprocess.py",
line 247, in call
with Popen(*popenargs, **kwargs) as p:

File "/Users/user/anaconda3/envs/deeplearning/lib/python3.5/subprocess.py",
line 676, in *init*
restore_signals, start_new_session)

File "/Users/user/anaconda3/envs/deeplearning/lib/python3.5/subprocess.py",
line 1289, in _execute_child
raise child_exception_type(errno_num, err_msg)

FileNotFoundError: [Errno 2] No such file or directory: 'fluidsynth'`

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bzamecnik/midi2audio/issues/2>, or mute the thread

**Comment by JakobFelixJulius** [comment]
Thanks for the quick reply!
how would I go about that?
After quick research, if I check
`python -c "import sys; print('\n'.join(sys.path))"`
 
within my desired environment, I get the (correct) following directories:

```
/Users/jakobsudau/anaconda3/envs/deeplearning/lib/python35.zip
/Users/jakobsudau/anaconda3/envs/deeplearning/lib/python3.5
/Users/jakobsudau/anaconda3/envs/deeplearning/lib/python3.5/plat-darwin
/Users/jakobsudau/anaconda3/envs/deeplearning/lib/python3.5/lib-dynload
/Users/jakobsudau/anaconda3/envs/deeplearning/lib/python3.5/site-packages
```

**Comment by bzamecnik** [comment]
Actually `sys.path` is for loading Python packages, while unix `$PATH` is
for executing programs. Check:

```
import os
os.environ('PATH')
```

and compare it to:

```
$ which fluidsynth
```

We run it as a subprocess.

Dne 24. 1. 2018 18:04 napsal uživatel "jakob.sudau" <
notifications@github.com>:

**Comment by JakobFelixJulius** [comment]
Oh ok, so I see now that fluidsynth is installed in `/usr/local/bin/fluidsynth`

and in my environment I only have these paths: `PATH:  /Users/username/anaconda3/envs/deeplearning/bin:/Users/username/anaconda3/bin:/usr/bin:/bin:/usr/sbin:/sbin`

where `/usr/local/bin` is not included.

in my base python environment I managed to get the midi2audio package working - here I have these paths: `PATH:  /Users/username/anaconda3/bin:/usr/bin:/bin:/usr/sbin:/sbin`

**Comment by JakobFelixJulius** [comment]
ok so I think I am getting there, it seems that when I launch Spyder (which I am using for editing & executing) via Anaconda then the `/usr/local/bin` entry of the `os.environ['PATH']` seems to get lost.

When I open Spyder via Terminal without Anaconda, everything is working and the `/usr/local/bin` entry is there.

**Comment by bzamecnik** [comment]
Good! :)
